name: Essentials
version: ${project.version}
main: io.github.bryanpaik.essentials.Essentials
api-version: 1.17

commands:
  home:
    description: Teleports you back to your bed.
    usage: /<command>
    permission: essentials.home
  tpa:
    description: Teleport request to player.
    usage: /<command>
    permission: essentials.tprequest
  tpaccept:
    description: Accepts an existing tp request.
    usage: /<command>
    permission: essentials.tpaccept
